diff --git a/Makefile b/Makefile
index a6a656f..60b038d 100644
--- a/Makefile
+++ b/Makefile
@@ -8,12 +8,10 @@ MY_CFLAGS += -DWITHOUT_NVME_PATCH
 ccflags-y += ${MY_CFLAGS}
 CC += ${MY_CFLAGS}
 
-KVERSION := $(KERNELRELEASE)
-ifeq ($(origin KERNELRELEASE), undefined)
-KVERSION := $(shell uname -r)
-endif
-
-KDIR := /lib/modules/$(KVERSION)/build
+KVERSION := linux-5.12.14
+KDIR := ../kernel/$(KVERSION)
+CRUXBASEDIR := $(shell dirname $$(pwd))
+CRUXROOTFS := $(CRUXBASEDIR)/tmp/rootfs
 PWD := $(shell pwd)
 
 .PHONY: all
@@ -26,3 +24,6 @@ clean:
 
 install:
 	$(MAKE) -C $(KDIR) M=$(PWD) modules_install
+
+install-rootfs:
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXROOTFS) -C $(KDIR) M=$(PWD) modules_install
