diff --git a/Makefile b/Makefile
index ea40afe..026562d 100644
--- a/Makefile
+++ b/Makefile
@@ -2,15 +2,14 @@ obj-m += apple-ibridge.o
 obj-m += apple-ib-tb.o
 obj-m += apple-ib-als.o
 
-KVERSION := $(KERNELRELEASE)
-ifeq ($(origin KERNELRELEASE), undefined)
-KVERSION := $(shell uname -r)
-endif
-KDIR := /lib/modules/$(KVERSION)/build
+KVERSION := linux-5.12.14
+KDIR := ../kernel/$(KVERSION)
+CRUXKBASEDIR := $(shell dirname $$(pwd))
+CRUXROOTFS := $(CRUXKBASEDIR)/tmp/rootfs
 PWD := $(shell pwd)
 
 all:
-	$(MAKE) -C $(KDIR) M=$(PWD) modules
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXROOTFS) -C $(KDIR) M=$(PWD) modules
 
 clean:
 	$(MAKE) -C $(KDIR) M=$(PWD) clean
@@ -18,3 +17,6 @@ clean:
 install:
 	$(MAKE) -C $(KDIR) M=$(PWD) modules_install
 
+install-rootfs:
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXROOTFS) -C $(KDIR) M=$(PWD) modules_install
+
