diff --git a/Makefile b/Makefile
index ea40afe..5230c4d 100644
--- a/Makefile
+++ b/Makefile
@@ -2,19 +2,17 @@ obj-m += apple-ibridge.o
 obj-m += apple-ib-tb.o
 obj-m += apple-ib-als.o
 
-KVERSION := $(KERNELRELEASE)
-ifeq ($(origin KERNELRELEASE), undefined)
-KVERSION := $(shell uname -r)
-endif
-KDIR := /lib/modules/$(KVERSION)/build
+KVERSION := "linux-5.12.14"
+KDIR := ../kernel/$(KVERSION)
+CRUXKPATH := ../tmp/rootfs
 PWD := $(shell pwd)
 
 all:
-	$(MAKE) -C $(KDIR) M=$(PWD) modules
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXKPATH) -C $(KDIR) M=$(PWD) modules
 
 clean:
-	$(MAKE) -C $(KDIR) M=$(PWD) clean
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXKPATH) -C $(KDIR) M=$(PWD) clean
 
 install:
-	$(MAKE) -C $(KDIR) M=$(PWD) modules_install
+	$(MAKE) INSTALL_MOD_PATH=$(CRUXKPATH) -C $(KDIR) M=$(PWD) modules_install
 
